// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsxigkwcJahAlevRd2SL6AK3dtm-WQgRM',
    appId: '1:217663422056:web:3c01f576a6b9926d7fc5dd',
    messagingSenderId: '217663422056',
    projectId: 'crunsee-70975',
    authDomain: 'crunsee-70975.firebaseapp.com',
    storageBucket: 'crunsee-70975.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQ6Mx_dIrAB3R3-RACRLvNPX17gx2vd0',
    appId: '1:217663422056:android:ed894c84c534ede27fc5dd',
    messagingSenderId: '217663422056',
    projectId: 'crunsee-70975',
    storageBucket: 'crunsee-70975.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsxigkwcJahAlevRd2SL6AK3dtm-WQgRM',
    appId: '1:217663422056:web:90513924dba7099e7fc5dd',
    messagingSenderId: '217663422056',
    projectId: 'crunsee-70975',
    authDomain: 'crunsee-70975.firebaseapp.com',
    storageBucket: 'crunsee-70975.firebasestorage.app',
  );
}
